name = "web-v1"
compatibility_date = "2024-04-01"
pages_build_output_dir = ".next"

[[r2_buckets]]
binding = "MY_BUCKET"   # ဒါက Backend code ထဲမှာ သုံးထားတာမို့ မပြောင်းပါနဲ့
bucket_name = "trail"   # ဒီနေရာမှာ 'kpanon-media' အစား 'trail' လို့ ပြောင်းပေးပါ (Dashboard ထဲကအတိုင်း)

[[d1_databases]]
binding = "DB"
database_name = "web-v1"
database_id = "9aca9532-3520-4061-b4ae-8f59b63fc4c9" # အစ်ကို့ Account ID နဲ့ မမှားပါစေနဲ့၊ D1 ID သီးသန့်ရှိပါတယ်