name = "kp-anon-website"
compatibility_date = "2024-04-01"
pages_build_output_dir = ".next"

[[r2_buckets]]
binding = "MY_BUCKET"   # ဒါက Backend code ထဲမှာ သုံးထားတာမို့ မပြောင်းပါနဲ့
bucket_name = "trail"   # ဒီနေရာမှာ 'kpanon-media' အစား 'trail' လို့ ပြောင်းပေးပါ (Dashboard ထဲကအတိုင်း)

[[d1_databases]]
binding = "DB"
database_name = "kpanon-db"
database_id = "8335c407-41d0-6aa6-8389-53c2828d6599" # အစ်ကို့ Account ID နဲ့ မမှားပါစေနဲ့၊ D1 ID သီးသန့်ရှိပါတယ်